on:
  pull_request:
  push:
    branches:
      - main
  release:
    types: [published]

jobs:
  event:
    runs-on: ubuntu-22.04
    steps:
      - name: event
        run: echo ${{ github.event_name }}
  deploy:
    if: ${{ github.event_name == 'release' }}
    runs-on: ubuntu-22.04
    steps:
      - name: publish
        run: echo publish
