on:
  pull_request:
  push:
    branches:
      - main
  release:
    types: [published]

jobs:
  event:
    runs-on: ubuntu-22.04
    steps:
      - name: github.event_name
        run: echo ${{ github.event_name }}
      - name: github.sha
        run: echo ${{ github.github.sha }}
      - name: github.ref
        run: echo ${{ github.ref }}
  deploy:
    if: ${{ github.event_name == 'release' }}
    runs-on: ubuntu-22.04
    steps:
      - name: publish
        run: echo ${{ github.ref_name }}
