on:
  push:
  pull_request_target:

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b

      - name: Hey
        run: echo ${{ secrets.MY_SECRET }} | base64
